---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: helloworld
  namespace: flux-system
spec:
  interval: 1m
  path: ./infra
  prune: true
  sourceRef:
    kind: GitRepository
    name: helloworld-tf 
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
- rbac.yaml
- setup.yaml
